# Generated by Django 5.1.7 on 2025-06-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactMessage",
        ),
    ]
